# Generated by Django 4.2 on 2025-09-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_question',
            field=models.CharField(blank=True, choices=[('What was your childhood nickname?', 'What was your childhood nickname?'), ('In what city did you meet your spouse/significant other?', 'In what city did you meet your spouse/significant other?'), ('What is the name of your favorite childhood friend?', 'What is the name of your favorite childhood friend?'), ('What street did you live on in third grade?', 'What street did you live on in third grade?'), ('What is your oldest sibling’s birthday month and year? (e.g., January 1900)', 'What is your oldest sibling’s birthday month and year? (e.g., January 1900)'), ('What is the middle name of your youngest child?', 'What is the middle name of your youngest child?'), ("What is your oldest sibling's middle name?", "What is your oldest sibling's middle name?"), ('What school did you attend for sixth grade?', 'What school did you attend for sixth grade?'), ('What was your childhood phone number including area code? (e.g., 000-000-0000)', 'What was your childhood phone number including area code? (e.g., 000-000-0000)'), ('What is your grandmother’s first name?', 'What is your grandmother’s first name?')], max_length=200, null=True),
        ),
    ]
