# Generated by Django 4.2 on 2025-09-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash on Delivery', 'Cash on Delivery'), ('Credit Card', 'Credit Card'), ('Jazz Cash', 'Jazz Cash'), ('Easypaisa', 'Easypaisa')], default='None', max_length=100, null=True),
        ),
    ]
