# Generated by Django 4.2 on 2025-09-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash on Delivery', 'Cash on Delivery'), ('Credit Card', 'Credit Card'), ('JazzCash', 'JazzCash'), ('Easypaisa', 'Easypaisa')], default='None', max_length=100, null=True),
        ),
    ]
