# Generated by Django 4.2 on 2025-09-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_notifications_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
